In [135]:
# Dependencies
import json
import requests
import pandas as pd

In [136]:
api_key = '3286c138a388ef8b9e598517a438a480860463e3'

In [1]:
#Vacant housing units = B25004_001E, 
# median home value = B25077_001E
# median year structures built = B25035_001E
url = 'https://api.census.gov/data/2013/acs1?get=NAME,B01003_001E,B25004_001E,B25077_001E,B25035_001E,B10010_001E&for=metropolitan%20statistical%20area/micropolitan%20statistical%20area:*&key='
#url = 'https://api.census.gov/data/2016/acs1?get=*&for=metropolitan%20statistical%20area/micropolitan%20statistical%20area:*&key='

#FORS
#metropolitan%20statistical%20area/micropolitan%20statistical%20area
#state
#congressional%20district

key_url = url + api_key

NameError: name 'api_key' is not defined

In [138]:
#base_url = 'https://api.census.gov/data/'
#year = '2016/'
#datasetAcronym = 'acs1/'
#query = '?get='

#full_url = base_url + year + datasetAcronym

#https://api.census.gov/data/2013/acs1?get=NAME,B02015_009E,B02015_009M&for=state:*&key=your key here

columns = {'NAME': 'Name of Metro Area',
            'B01003_001E' : 'Total Population',
            'B25004_001E' : 'Vacant Housing Units',
            'B25077_001E' : 'Median Home Value',
            'B25035_001E' : 'Median Year Sructures Built',
            'metropolitan statistical area/micropolitan statistical area' : 'Area ID'
          }

In [139]:
census_response = requests.get(key_url)
census_json = census_response.json()

dataFrame =pd.DataFrame(census_json)
dataFrame.columns = dataFrame.iloc[0]
dataFrame = dataFrame.drop([0])
dataFrame = dataFrame.rename(columns=columns)

In [140]:
dataFrame

,Name of Metro Area,Total Population,Vacant Housing Units,Median Home Value,Median Year Sructures Built,Area ID
1,"Aguadilla-Isabela, PR Metro Area",327847,34856,97400,1980,10380
2,"Arecibo, PR Metro Area",195036,14383,102000,1983,11640
3,"Guayama, PR Metro Area",81217,6796,90500,1984,25020
4,"Mayagüez, PR Metro Area",101856,12347,103500,1973,32420
5,"Ponce, PR Metro Area",333527,27022,95700,1978,38660
6,"San Germán, PR Metro Area",134623,21425,98500,1984,41900
7,"San Juan-Carolina-Caguas, PR Metro Area",2288977,186562,135200,1977,41980
8,"Aberdeen, WA Micro Area",71078,8275,156300,1971,10140
9,"Abilene, TX Metro Area",168144,9111,86800,1970,10180
10,"Adrian, MI Micro Area",99188,6024,108900,1968,10300
11,"Akron, OH Metro Area",705686,31058,136600,1966,10420
12,"Alamogordo, NM Micro Area",65616,7599,102700,1983,10460
13,"Albany, GA Metro Area",156277,9679,104300,1980,10500
14,"Albany, OR Metro Area",118765,4921,173800,1974,10540
15,"Albany-Schenectady-Troy, NY Metro Area",877905,47041,195600,1962,10580
16,"Albertville, AL Micro Area",94760,6420,117100,1980,10700
17,"Albuquerque, NM Metro Area",901932,39716,176900,1983,10740
18,"Alexandria, LA Metro Area",154753,10185,119500,1978,10780
19,"Allentown-Bethlehem-Easton, PA-NJ Metro Area",827048,29675,197300,1967,10900
20,"Altoona, PA Metro Area",126314,None,115200,1954,11020
21,"Amarillo, TX Metro Area",259164,10003,122900,1973,11100
22,"Ames, IA Metro Area",92406,None,158100,1976,11180
23,"Anchorage, AK Metro Area",396142,21289,275100,1984,11260
24,"Ann Arbor, MI Metro Area",354240,10723,207500,1975,11460
25,"Anniston-Oxford-Jacksonville, AL Metro Area",116736,9209,92900,1975,11500
26,"Appleton, WI Metro Area",229962,4929,159000,1977,11540
27,"Asheville, NC Metro Area",437657,32962,183100,1985,11700
28,"Ashtabula, OH Micro Area",99811,6358,103900,1958,11780
29,"Athens, TX Micro Area",78675,11505,90500,1985,11980
30,"Athens-Clarke County, GA Metro Area",197357,9446,154500,1985,12020
...,...,...,...,...,...,...
486,"Visalia-Porterville, CA Metro Area",454143,10914,160400,1982,47300
487,"Waco, TX Metro Area",257083,10996,109000,1977,47380
488,"Walla Walla, WA Metro Area",63361,None,171100,1970,47460
489,"Warner Robins, GA Metro Area",185623,8603,124300,1990,47580
490,"Warsaw, IN Micro Area",77963,8584,128100,1976,47700
491,"Washington-Arlington-Alexandria, DC-VA-MD-WV M...",5950214,145874,373500,1979,47900
492,"Waterloo-Cedar Falls, IA Metro Area",169484,5487,131400,1960,47940
493,"Watertown-Fort Atkinson, WI Micro Area",84509,None,162200,1970,48020
494,"Watertown-Fort Drum, NY Metro Area",119504,15682,143800,1967,48060
495,"Wausau, WI Metro Area",135416,3629,141900,1974,48140
496,"Weirton-Steubenville, WV-OH Metro Area",124718,7088,84800,1957,48260
497,"Wenatchee, WA Metro Area",113438,10339,222900,1979,48300
498,"Wheeling, WV-OH Metro Area",145757,8359,93500,1956,48540
499,"Whitewater-Elkhorn, WI Micro Area",102945,11209,185700,1976,48580
500,"Wichita, KS Metro Area",637989,25930,121700,1973,48620
501,"Wichita Falls, TX Metro Area",151201,7457,88700,1970,48660
502,"Williamsport, PA Metro Area",116754,None,133600,1960,48700
503,"Wilmington, NC Metro Area",268601,23535,190700,1989,48900
504,"Wilson, NC Micro Area",81667,None,113900,1984,48980
505,"Winchester, VA-WV Metro Area",126900,7560,196000,1982,49020
506,"Winston-Salem, NC Metro Area",650820,32955,144000,1980,49180
507,"Wisconsin Rapids-Marshfield, WI Micro Area",73959,None,120800,1970,49220
508,"Wooster, OH Micro Area",115071,None,130700,1969,49300
509,"Worcester, MA-CT Metro Area",926710,31038,241400,1962,49340
510,"Yakima, WA Metro Area",247044,6156,159800,1976,49420
511,"York-Hanover, PA Metro Area",438965,14677,165300,1973,49620
512,"Youngstown-Warren-Boardman, OH-PA Metro Area",555506,28845,97400,1960,49660
513,"Yuba City, CA Metro Area",168690,4894,174200,1978,49700
514,"Yuma, AZ Metro Area",201201,19866,108800,1992,49740
515,"Zanesville, OH Micro Area",85231,3475,96800,1967,49780